name: c2c-artifacts # This sets the project name
services:
  backend:
    build:
      context: ./API
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./UI
    container_name: flaskui
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
