apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
  namespace: default
  labels:
    app: {{ include "mychart.name" . }}
spec:
  selector:
    app: {{ include "mychart.name" . }}
  type: LoadBalancer
  ports:
    - name: api
      port: 8000
      targetPort: 8000
    - name: ui
      port: 5000
      targetPort: 5000
