apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: {{ include "my-chart.fullname" . }}-frontend
  name: {{ include "my-chart.fullname" . }}-frontend
spec:
  ports:
    - name: "5000"
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    io.kompose.service: {{ include "my-chart.fullname" . }}-frontend
