apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-ui
  labels:
    app: {{ include "mychart.name" . }}
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mychart.name" . }}
      component: ui
  template:
    metadata:
      labels:
        app: {{ include "mychart.name" . }}
        component: ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.ui.image }}
          ports:
            - containerPort: 5000
